import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    // 1. Konfigurasi Content (Path ke file-file Anda)
        content: [
                './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
                        './storage/framework/views/*.php',
                                './resources/views/**/*.blade.php',
                                        // Kita beri komentar dulu path Filament, akan diaktifkan nanti
                                                // './vendor/filament/**/*.blade.php',
                                                    ],

                                                        // 2. Safelist untuk mode "Gudang Penuh"
                                                            safelist: [
                                                                    { pattern: /.*/ }
                                                                        ],

                                                                            // 3. Konfigurasi Tema (Termasuk kustomisasi dengan Variabel CSS)
                                                                                theme: {
                                                                                        extend: {
                                                                                                    colors: {
                                                                                                                    primary: 'rgb(var(--color-primary) / <alpha-value>)',
                                                                                                                                    secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
                                                                                                                                                    accent: 'rgb(var(--color-accent) / <alpha-value>)',
                                                                                                                                                                    'text-base': 'rgb(var(--color-text-base) / <alpha-value>)',
                                                                                                                                                                                    'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
                                                                                                                                                                                                    'bg-base': 'rgb(var(--color-bg-base) / <alpha-value>)',
                                                                                                                                                                                                                    'bg-surface': 'rgb(var(--color-bg-surface) / <alpha-value>)',
                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                            fontFamily: {
                                                                                                                                                                                                                                                            sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                        // 4. Daftar Semua Plugin Anda
                                                                                                                                                                                                                                                                                            plugins: [
                                                                                                                                                                                                                                                                                                    forms, // Ini adalah @tailwindcss/forms yang diimpor di atas
                                                                                                                                                                                                                                                                                                            require('@tailwindcss/typography'),
                                                                                                                                                                                                                                                                                                                    require('@tailwindcss/aspect-ratio'),
                                                                                                                                                                                                                                                                                                                            require('daisyui'),
                                                                                                                                                                                                                                                                                                                                    require('tailwindcss-animate'),
                                                                                                                                                                                                                                                                                                                                            require('tailwind-scrollbar-hide'),
                                                                                                                                                                                                                                                                                                                                                    require('tailwindcss-debug-screens'),
                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                // 5. Konfigurasi untuk DaisyUI (Opsional, tapi bagus untuk ada)
                                                                                                                                                                                                                                                                                                                                                                    daisyui: {
                                                                                                                                                                                                                                                                                                                                                                            themes: ["light", "dark", "cupcake", "bumblebee", "emerald", "synthwave"],
                                                                                                                                                                                                                                                                                                                                                                                    base: true,
                                                                                                                                                                                                                                                                                                                                                                                            styled: true,
                                                                                                                                                                                                                                                                                                                                                                                                    utils: true,
                                                                                                                                                                                                                                                                                                                                                                                                            logs: true,
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                };